const mongoose = require('mongoose');

const mentorshipSchema = new mongoose.Schema(
  {
    menteeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    mentorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    goals: [String],
    status: {
      type: String,
      enum: ['pending', 'active', 'completed', 'paused'],
      default: 'active',
    },
    sessionFrequency: {
      type: String,
      enum: ['weekly', 'biweekly', 'monthly'],
    },
    startDate: Date,
    endDate: Date,
    notes: String,
    compatibilityScore: Number, // Generated by Gemini AI
    learningPathway: mongoose.Schema.Types.Mixed, // AI-generated pathway
    progress: {
      goalsCompleted: [String],
      milestonesReached: [String],
      lastUpdate: Date,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model('Mentorship', mentorshipSchema);
